"""Interference + volume check.  Run: freecadcmd ai-files/cad/check_cad.py  -> interference.md, volumes.md, work/check.json"""
import json, itertools, Part, FreeCAD as App
from FreeCAD import Vector as V
CAD='/home/chithi/Desktop/DesktopSpeaker/ai-files/cad/'; W=CAD+'work/'
m=json.load(open(W+'meta.json')); P=m['params']
S={o['name']:(o,Part.read(W+'brep/'+o['file'])) for o in m['objs']}
names=list(S)
def intended(a,b):
    ga,gb=S[a][0]['group'],S[b][0]['group']
    pair={ga,gb}
    if pair=={'pcb','pcb_parts'}: return 'through-hole/mid-mount pins and body below PCB top (model pins sit in the board)'
    return None
rows=[];intend=[]
THR=0.5
for a,b in itertools.combinations(names,2):
    sa,sb=S[a][1],S[b][1]
    if not sa.BoundBox.intersect(sb.BoundBox): continue
    try: v=sa.common(sb).Volume
    except Exception as e: v=-1
    if v>THR or v<0:
        why=intended(a,b)
        (intend if why else rows).append((a,b,round(v,2),why))
rows.sort(key=lambda r:-r[2]); intend.sort(key=lambda r:-r[2])
# volumes
t=P['wall']; Wd,Hd,Dd=P['W'],P['H'],P['D']; YB=Dd-t
def box(x0,x1,y0,y1,z0,z1): return Part.makeBox(x1-x0,y1-y0,z1-z0,V(x0,y0,z0))
cav=box(-Wd/2+t,Wd/2-t,t,YB,t,Hd-t)
chx=P['ch_x']; RB=P['ch_top']+P['roof']
ch_in=box(-chx,chx,P['ch_y0']+t,YB,t,P['ch_top'])
ch_out=box(-chx-t,chx+t,P['ch_y0'],YB,t,RB)
main=cav.cut(ch_out)
def disp(region):
    tot=0;items=[]
    for n,(o,s) in S.items():
        if not s.BoundBox.intersect(region.BoundBox): continue
        v=s.common(region).Volume
        if v>0.5: items.append((n,v)); tot+=v
    return tot,items
dw,iw=disp(ch_in); dm,im=disp(main)
gw,gm=ch_in.Volume,main.Volume
out=dict(woof_gross=gw,woof_disp=dw,woof_net=gw-dw,main_gross=gm,main_disp=dm,main_net=gm-dm,total_internal=cav.Volume,
         ext=Wd*Hd*Dd, items_w=iw, items_m=im, overlaps=rows, intended=intend)
json.dump(out,open(W+'check.json','w'),indent=1)
with open(CAD+'volumes.md','w') as f:
    f.write('# Internal volumes (generated by check_cad.py)\n\nOuter %.0f x %.0f x %.0f mm (X x Z x Y, lid included), wall %.0f mm; external volume %.2f L; total internal cavity %.3f L.\n\n'%(Wd,Hd,Dd,t,Wd*Hd*Dd/1e6,cav.Volume/1e6))
    f.write('| Chamber | Gross (L) | Displaced by parts/bosses/pads (L) | Net (L) | Target |\n|---|---|---|---|---|\n')
    f.write('| Woofer (sealed, own chamber; rear wall = lid) | %.3f | %.3f | **%.3f** | 0.45-0.60 |\n'%(gw/1e6,dw/1e6,(gw-dw)/1e6))
    f.write('| Main (2 front drivers + battery + PCB, shared) | %.3f | %.3f | **%.3f** | >= 0.80 |\n\n'%(gm/1e6,dm/1e6,(gm-dm)/1e6))
    f.write('Walls and partitions between the chambers are not counted in either (gross = air region bounded by the wall inner faces).\n\n')
    for ttl,it in (('Woofer chamber displacement',iw),('Main chamber displacement',im)):
        f.write('## %s (mm3, >0.5)\n\n'%ttl)
        for n,v in sorted(it,key=lambda x:-x[1])[:25]: f.write('- %s: %.0f\n'%(n,v))
        f.write('\n')
with open(CAD+'interference.md','w') as f:
    f.write('# Interference check (generated by check_cad.py)\n\nPairwise Boolean common volume of all %d solids, threshold %.1f mm3.\n\n'%(len(names),THR))
    f.write('## Unintended overlaps (%d)\n\n'%len(rows))
    f.write('| A | B | mm3 |\n|---|---|---|\n')
    for a,b,v,_ in rows: f.write('| %s | %s | %.2f |\n'%(a,b,v))
    f.write('\n## Intended overlaps (%d): connector/IC pins sitting in the PCB model\n\n| A | B | mm3 |\n|---|---|---|\n'%len(intend))
    for a,b,v,_ in intend: f.write('| %s | %s | %.2f |\n'%(a,b,v))
print('unintended',len(rows),'intended',len(intend)); print(json.dumps({k:round(v/1e6,3) for k,v in out.items() if k.startswith(('woof','main','total'))}))
for r in rows[:40]: print(r[:3])
